<?php defined('ABSPATH') || exit;
if($editor): ?>
<div class="aspire-directory-preview"><p>ASPIRE PROPERTY DIRECTORY</p><h3><?php echo count(Aspire_Atlas::collection()['features']); ?> published properties</h3><dl><div><dt>Default view</dt><dd><?php echo $view==='split'?'Split':'List'; ?></dd></div><div><dt>Map</dt><dd><?php echo $show_map?'Enabled':'Off'; ?></dd></div><div><dt>Filters</dt><dd>Property Type · Transaction · Size · Area</dd></div><div><dt>Properties per load</dt><dd><?php echo $per_load?:'All'; ?></dd></div></dl><p>Live inventory and map are available on the published page.</p></div>
<?php return;endif; ?>
<section <?php echo get_block_wrapper_attributes(array('class'=>'aspire-directory')); ?> aria-label="Aspire property directory" data-directory data-view="<?php echo esc_attr($view); ?>" data-per-load="<?php echo esc_attr($per_load); ?>" data-endpoint="<?php echo esc_url(add_query_arg('directory','1',rest_url('aspire/v1/atlas/properties'))); ?>" data-base="<?php echo esc_url(get_permalink()); ?>" <?php if($show_map): ?>data-map-style="<?php echo esc_url(add_query_arg('ver',filemtime(dirname(ASPIRE_CORE_FILE).'/directory/build/map.css'),plugins_url('directory/build/map.css',ASPIRE_CORE_FILE))); ?>" data-map-module="<?php echo esc_url(add_query_arg('ver',filemtime(dirname(ASPIRE_CORE_FILE).'/directory/build/map.mjs'),plugins_url('directory/build/map.mjs',ASPIRE_CORE_FILE))); ?>" data-worker="<?php echo esc_url(plugins_url('atlas/build/worker.js',ASPIRE_CORE_FILE)); ?>" data-tiles="<?php echo esc_url(content_url('/uploads/aspire-atlas/houston.pmtiles')); ?>" data-glyphs="<?php echo esc_attr(content_url('/uploads/aspire-atlas/fonts/{fontstack}/{range}.pbf')); ?>"<?php endif; ?>>
 <nav class="directory-types" aria-label="Quick property types"><?php foreach(array('retail'=>'Retail','office'=>'Office','industrial-flex'=>'Industrial / Flex','land'=>'Land','office-condo'=>'Office Condos') as $slug=>$label):if(!term_exists($slug,'property_type'))continue; ?><button type="button" data-quick-type="<?php echo esc_attr($slug); ?>" aria-pressed="false"><?php echo esc_html($label); ?></button><?php endforeach; ?></nav>
 <form class="directory-filters" aria-label="Filter properties">
  <label>PROPERTY TYPE<select name="type"><option value="">All Properties</option><?php foreach(is_wp_error($types)?array():$types as $term): ?><option value="<?php echo esc_attr($term->slug); ?>"><?php echo esc_html($term->name); ?></option><?php endforeach; ?></select></label>
  <label>TRANSACTION<select name="transaction"><option value="">All Transactions</option><?php foreach(is_wp_error($transactions)?array():$transactions as $term): ?><option value="<?php echo esc_attr($term->slug); ?>"><?php echo esc_html($term->name); ?></option><?php endforeach; ?></select></label>
  <label><span class="directory-size-label">SIZE</span><select name="size"><option value="">Any Size</option></select></label>
  <label>AREA<select name="area"><option value="">All Houston</option></select></label>
  <button class="directory-reset" type="button">RESET <span aria-hidden="true">↺</span></button>
 </form>
 <div class="directory-toolbar"><p class="directory-count" role="status" aria-live="polite" aria-atomic="true">Loading opportunities…</p><label class="directory-sort">Sort by <select name="sort"><option value="featured">Featured</option><option value="newest">Newest</option><option value="largest">Largest</option></select></label><?php if($show_map): ?><div class="directory-views" role="group" aria-label="Directory view"><button type="button" data-view-choice="split" aria-pressed="<?php echo $view==='split'?'true':'false'; ?>">SPLIT</button><button type="button" data-view-choice="list" aria-pressed="<?php echo $view==='list'?'true':'false'; ?>">LIST</button></div><?php endif; ?></div>
 <p class="directory-sort-note" hidden>Buildings ranked by square feet; land ranked separately by acres.</p>
 <div class="directory-layout">
  <div class="directory-inventory"><div class="directory-error" role="status" hidden><h2>Opportunities are temporarily unavailable.</h2><p>Please reload to try again, or talk to Aspire about current availability.</p><a href="<?php echo esc_url(home_url('/contact/')); ?>">TALK TO ASPIRE →</a></div><div class="directory-empty" hidden><h2>Nothing currently matches those filters.</h2><p>Try widening your search, or create a real estate brief so Aspire has a clearer picture of what you're looking for.</p><button type="button" class="directory-reset">RESET FILTERS</button><a href="<?php echo esc_url(home_url('/')); ?>">CREATE MY REAL ESTATE BRIEF →</a></div><ul class="directory-cards" aria-label="Matching properties"></ul><button type="button" class="directory-more" hidden>LOAD MORE PROPERTIES</button><p class="directory-selection sr-only" role="status"></p></div>
  <?php if($show_map): ?><aside class="directory-map-panel" aria-label="Houston property locations"><div class="directory-map"></div><p class="directory-map-status" role="status">Loading Houston map…</p><div class="directory-map-tools"><label>Locate a property<select class="directory-map-select"><option value="">Choose a property</option></select></label></div><div class="directory-map-preview" hidden></div><p class="directory-attribution">© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap contributors</a> · <a href="https://protomaps.com" target="_blank" rel="noopener">Protomaps</a></p></aside><?php endif; ?>
 </div>
 <noscript><p>Enable JavaScript for the interactive filters. Available properties:</p><ul><?php foreach(Aspire_Atlas::collection()['features'] as $feature): ?><li><a href="<?php echo esc_url($feature['properties']['permalink']); ?>"><?php echo esc_html($feature['properties']['displayTitle']); ?></a></li><?php endforeach; ?></ul></noscript>
</section>
