<?php defined( 'ABSPATH' ) || exit; ?>
<footer class="site-footer"><div class="container">
	<div class="footer-grid"><div class="footer-brand"><?php aspirecre_brand(); ?><div class="contact-details"><h2>Contact</h2>
	<?php $email = get_theme_mod( 'aspirecre_contact_email', '' ); $phone = get_theme_mod( 'aspirecre_contact_phone', '' ); $address = get_theme_mod( 'aspirecre_contact_address', '' ); ?>
	<?php if ( $address ) : ?><address><?php echo nl2br( esc_html( $address ) ); ?></address><?php endif; ?>
	<?php if ( $phone ) : ?><a href="<?php echo esc_url( 'tel:' . preg_replace( '/[^0-9+]/', '', $phone ) ); ?>"><?php echo esc_html( $phone ); ?></a><?php endif; ?>
	<?php if ( $email ) : ?><a href="<?php echo esc_url( 'mailto:' . sanitize_email( $email ) ); ?>"><?php echo esc_html( $email ); ?></a><?php endif; ?>
	<a class="footer-contact-link" href="<?php echo esc_url( is_front_page() ? aspirecre_home_destination( 'contact' ) : home_url( '/contact/' ) ); ?>">Talk to Aspire <span aria-hidden="true">↗</span></a></div></div>
	<nav aria-labelledby="footer-properties"><h2 id="footer-properties">Properties</h2><ul><li><a href="<?php echo esc_url( home_url( '/properties/' ) ); ?>">All Properties</a></li>
	<?php foreach ( array( 'Retail', 'Office', 'Industrial / Flex', 'Land', 'Office Condo' ) as $name ) : $term = get_term_by( 'name', $name, 'property_type' ); $url = $term ? add_query_arg( 'property_type', $term->slug, home_url( '/properties/' ) ) : home_url( '/properties/' ); ?><li><a href="<?php echo esc_url( $url ); ?>"><?php echo esc_html( 'Office Condo' === $name ? 'Office Condos' : $name ); ?></a></li><?php endforeach; ?></ul></nav>
	<nav aria-labelledby="footer-services"><h2 id="footer-services">Services</h2><ul><?php $footer_services = array( 'tenant-representation' => 'Tenant Representation', 'landlord-representation' => 'Landlord Representation', 'investment-sales' => 'Investment Sales', 'property-management' => 'Property Management', 'cre-consulting' => 'Consulting' ); if ( is_front_page() ) { $footer_services = array_slice( $footer_services, 0, 3, true ) + array( 'investor-developer-services' => 'Investor & Developer Services' ) + array_slice( $footer_services, 3, null, true ); $footer_services['cre-consulting'] = 'CRE Consulting'; } foreach ( $footer_services as $service_key => $service ) : ?><li><a href="<?php echo esc_url( is_front_page() ? aspirecre_home_destination( $service_key ) : home_url( '/services/' ) ); ?>"><?php echo esc_html( $service ); ?></a></li><?php endforeach; ?></ul></nav>
	<nav aria-labelledby="footer-company"><h2 id="footer-company">Company</h2><ul><?php foreach ( array( 'About' => '/about/', 'Team' => '/our-team/', 'Insights' => '/insights/', 'Careers' => '/careers/', 'Contact' => '/contact/' ) as $label => $path ) : if ( is_front_page() && 'Careers' === $label && ! get_page_by_path( 'careers' ) ) { continue; } ?><li><a href="<?php echo esc_url( is_front_page() && 'Careers' !== $label ? aspirecre_home_destination( strtolower( $label ) ) : home_url( $path ) ); ?>"><?php echo esc_html( $label ); ?></a></li><?php endforeach; ?></ul></nav></div>
	<div class="footer-bottom"><p>© <?php echo esc_html( wp_date( 'Y' ) ); ?> Aspire Commercial. All rights reserved.</p><ul class="legal-links">
	<?php foreach ( array( 'trec_iabs_url' => 'TREC Information About Brokerage Services', 'trec_notice_url' => 'TREC Consumer Protection Notice', 'privacy_legal_url' => 'Privacy / Legal' ) as $key => $label ) : $url = get_theme_mod( 'aspirecre_' . $key, '' ); ?><li><?php if ( $url ) : ?><a href="<?php echo esc_url( $url ); ?>"><?php echo esc_html( $label ); ?></a><?php else : ?><span><?php echo esc_html( $label ); ?> <span class="visually-hidden">— link not yet supplied</span></span><?php endif; ?></li><?php endforeach; ?></ul></div>
</div></footer>
<?php wp_footer(); ?>
</body></html>
