<?php
/** Dynamic commercial-property dossier. */
defined('ABSPATH') || exit;
get_header();
while(have_posts()):the_post();$d=AspireCRE_Property_Dossier::data(get_the_ID());
$sections=array();if($d['has_body']||$d['highlights'])$sections['overview']='Overview';if($d['suites'])$sections['availability']='Availability';if($d['groups']||$d['notes'])$sections['details']='Property Details';if($d['gallery'])$sections['gallery']='Gallery';if($d['address']||$d['locality']||$d['map'])$sections['location']='Location';$sections['contact']='Contact';
?>
<main id="main-content" class="property-dossier"><article aria-labelledby="property-title">
 <div class="dossier-breadcrumb"><a href="<?php echo esc_url(home_url('/properties/')); ?>">← ALL PROPERTIES</a><span>ASPIRE COMMERCIAL</span></div>
 <header class="dossier-opening">
  <div class="dossier-hero-media"><?php if(AspireCRE_Property_Dossier::attachment((int)get_post_thumbnail_id(),true)):echo wp_get_attachment_image(get_post_thumbnail_id(),'full',false,array('class'=>'dossier-hero-image','sizes'=>'(max-width: 800px) 100vw, 62vw','loading'=>'eager','fetchpriority'=>'high','alt'=>get_post_meta(get_post_thumbnail_id(),'_wp_attachment_image_alt',true)?:$d['title']));else: ?><div class="dossier-image-fallback"><span aria-hidden="true">A</span><p>ASPIRE COMMERCIAL</p></div><?php endif; ?><?php if($d['gallery']): ?><a class="dossier-gallery-link" href="#property-gallery">VIEW GALLERY →</a><?php endif; ?></div>
  <div class="dossier-summary"><p class="dossier-eyebrow"><?php echo esc_html(implode(' · ',array_filter(array($d['type']->name??'',$d['transaction']->name??'')))); ?></p><h1 id="property-title"><?php echo esc_html($d['title']); ?></h1><?php if($d['locality']): ?><p class="dossier-locality"><?php echo esc_html($d['locality']); ?></p><?php endif; ?>
   <?php if($d['hero']): ?><dl class="dossier-primary-metrics"><?php foreach($d['hero'] as $label=>$value): ?><div><dt><?php echo esc_html($label); ?></dt><dd><?php echo esc_html($value); ?></dd></div><?php endforeach; ?></dl><?php endif; ?>
   <div class="dossier-actions"><?php if($d['brochure']): ?><a class="dossier-button" href="<?php echo esc_url(wp_get_attachment_url($d['brochure'])); ?>" download aria-label="<?php echo esc_attr('Download brochure for '.$d['title'].' (PDF)'); ?>">DOWNLOAD BROCHURE →</a><?php endif; ?><a class="dossier-button <?php echo $d['brochure']?'dossier-button-outline':''; ?>" href="tel:+17139332001">TALK TO ASPIRE →</a><a class="dossier-text-link" href="<?php echo esc_url(home_url('/')); ?>">CREATE MY REAL ESTATE BRIEF →</a></div>
  </div>
 </header>
 <nav class="dossier-nav" aria-label="Property sections"><?php foreach($sections as $key=>$label): ?><a href="#property-<?php echo esc_attr($key); ?>"><?php echo esc_html($label); ?></a><?php endforeach; ?></nav>
 <div class="dossier-content">
 <?php if(isset($sections['overview'])): ?><section id="property-overview" class="dossier-section dossier-overview" aria-label="Property overview">
  <?php if($d['has_body']): ?><div><h2>PROPERTY OVERVIEW</h2><div class="dossier-body"><?php the_content(); ?></div></div><?php endif; ?>
  <?php if($d['highlights']): ?><div class="dossier-highlights"><h2>PROPERTY HIGHLIGHTS</h2><ul><?php foreach($d['highlights'] as $line): ?><li><?php echo esc_html($line); ?></li><?php endforeach; ?></ul></div><?php endif; ?>
 </section><?php endif; ?>
 <?php if($d['suites']): ?><section id="property-availability" class="dossier-section"><h2>AVAILABILITY</h2><div class="dossier-table-scroll" role="region" aria-label="Suite availability" tabindex="0"><table><caption class="dossier-sr-only">Suite availability at <?php echo esc_html($d['title']); ?></caption><thead><tr><?php foreach($d['columns'] as $label): ?><th scope="col"><?php echo esc_html($label); ?></th><?php endforeach; ?></tr></thead><tbody><?php foreach($d['suites'] as $suite): ?><tr><?php foreach($d['columns'] as $key=>$label): ?><td><?php echo $suite[$key]!==''?esc_html($suite[$key]):'<span aria-label="Not provided">—</span>'; ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
 <?php if(isset($sections['details'])): ?><section id="property-details" class="dossier-section"><h2>PROPERTY DETAILS</h2><div class="dossier-detail-grid"><?php foreach($d['groups'] as $label=>$rows): ?><section><h3><?php echo esc_html($label); ?></h3><dl><?php foreach($rows as $key=>$value): ?><div><dt><?php echo esc_html($key); ?></dt><dd><?php echo esc_html($value); ?></dd></div><?php endforeach; ?></dl></section><?php endforeach; ?></div><?php if($d['notes']): ?><div class="dossier-detail-notes"><?php foreach($d['notes'] as $label=>$lines): ?><section><h3><?php echo esc_html($label); ?></h3><ul><?php foreach($lines as $line): ?><li><?php echo esc_html($line); ?></li><?php endforeach; ?></ul></section><?php endforeach; ?></div><?php endif; ?></section><?php endif; ?>
 <?php if($d['gallery']): ?><section id="property-gallery" class="dossier-section"><h2>GALLERY</h2><div class="dossier-gallery"><?php foreach($d['gallery'] as $image): ?><a href="<?php echo esc_url(wp_get_attachment_url($image)); ?>" aria-label="<?php echo esc_attr('View full image: '.(get_post_meta($image,'_wp_attachment_image_alt',true)?:$d['title'])); ?>"><?php echo wp_get_attachment_image($image,'large',false,array('loading'=>'lazy','sizes'=>'(max-width: 800px) 100vw, 50vw','alt'=>get_post_meta($image,'_wp_attachment_image_alt',true)?:$d['title'])); ?></a><?php endforeach; ?></div></section><?php endif; ?>
 <?php if(isset($sections['location'])): ?><section id="property-location" class="dossier-section"><div class="dossier-location-heading"><h2>LOCATION</h2><address><?php echo esc_html($d['address']); ?><?php if($d['address']&&$d['locality']): ?><br><?php endif; ?><?php echo esc_html($d['locality']); ?></address></div>
 <?php if($d['map']): ?><div class="dossier-map-root" data-property-map data-feature="<?php echo esc_attr(wp_json_encode($d['map'])); ?>" data-map-module="<?php echo esc_url(plugins_url('directory/build/map.mjs',ASPIRE_CORE_FILE)); ?>" data-map-style="<?php echo esc_url(plugins_url('directory/build/map.css',ASPIRE_CORE_FILE)); ?>" data-worker="<?php echo esc_url(plugins_url('atlas/build/worker.js',ASPIRE_CORE_FILE)); ?>" data-tiles="<?php echo esc_url(content_url('/uploads/aspire-atlas/houston.pmtiles')); ?>" data-glyphs="<?php echo esc_attr(content_url('/uploads/aspire-atlas/fonts/{fontstack}/{range}.pbf')); ?>"><div class="directory-map-panel"><div class="directory-map"></div><p class="directory-map-status" role="status">Property map loads as you approach.</p><div class="directory-map-preview" hidden></div><p class="dossier-map-caption"><?php echo esc_html($d['title']); ?></p><p class="dossier-attribution">© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap contributors</a> · <a href="https://protomaps.com" target="_blank" rel="noopener">Protomaps</a></p></div></div><?php endif; ?></section><?php endif; ?>
 <?php if($d['brokers']): ?><section class="dossier-section dossier-advisors" aria-labelledby="dossier-advisors-heading"><h2 id="dossier-advisors-heading">YOUR ASPIRE ADVISORS</h2><div class="dossier-advisor-grid"><?php foreach($d['brokers'] as $broker):$name=get_the_title($broker);$phone=AspireCRE_Property_Dossier::text($broker,'phone');$email=sanitize_email(AspireCRE_Property_Dossier::text($broker,'email')); ?><article><?php echo get_the_post_thumbnail($broker,'aspire-person',array('loading'=>'lazy','alt'=>$name)); ?><div><h3><a href="<?php echo esc_url(get_permalink($broker)); ?>"><?php echo esc_html($name); ?></a></h3><?php if(AspireCRE_Property_Dossier::text($broker,'job_title')): ?><p><?php echo esc_html(AspireCRE_Property_Dossier::text($broker,'job_title')); ?></p><?php endif; ?><?php if($phone&&preg_match('/[0-9]/',$phone)): ?><a href="tel:<?php echo esc_attr(preg_replace('/[^+0-9]/','',$phone)); ?>"><?php echo esc_html($phone); ?></a><?php endif; ?><?php if(is_email($email)): ?><a href="mailto:<?php echo esc_attr($email); ?>"><?php echo esc_html($email); ?></a><?php endif; ?><a class="dossier-text-link" href="<?php echo esc_url(get_permalink($broker)); ?>">VIEW PROFILE →</a></div></article><?php endforeach; ?></div></section><?php endif; ?>
 </div>
 <section id="property-contact" class="dossier-contact"><div><h2>INTERESTED IN THIS PROPERTY?</h2><p>Talk with Aspire about availability, pricing or whether this opportunity fits what you're looking for.</p></div><div class="dossier-actions"><a class="dossier-button" href="tel:+17139332001">TALK TO ASPIRE →</a><a class="dossier-text-link" href="<?php echo esc_url(home_url('/')); ?>">CREATE MY REAL ESTATE BRIEF →</a></div></section>
</article></main>
<?php endwhile;get_footer(); ?>
