import test from 'node:test';
import assert from 'node:assert/strict';
import {filter,sort,fromURL,toURL,defaults,cardData,areas} from '../src/data.js';
const f=(id,type,transaction,availableSf,buildingSf,lotAcres,extras={})=>({type:'Feature',id,geometry:{type:'Point',coordinates:[-95.65,29.75]},properties:{title:`Property ${id}`,displayTitle:`Display ${id}`,propertyType:{slug:type,label:type},transactionType:{slug:transaction,label:transaction},location:{city:'Houston',state:'TX'},metrics:{availableSf,buildingSf,lotAcres},pricing:{},directory:{featured:false,publishedAt:`2026-01-0${id}T00:00:00Z`},...extras}});
const inventory=[f(1,'retail','for-lease',4999,6000,2),f(2,'industrial-flex','for-sale-or-lease',10000,20000,3),f(3,'office','for-sale',null,50000,4),f(4,'land','ground-lease',null,90000,2.21)];
test('all inventory by default, taxonomy shortcuts, exact and dual transaction semantics',()=>{assert.equal(filter(inventory,defaults()).length,4);assert.deepEqual(filter(inventory,{...defaults(),transaction:'for-lease'}).map(f=>f.id),[1,2]);assert.deepEqual(filter(inventory,{...defaults(),transaction:'for-sale'}).map(f=>f.id),[2,3]);assert.deepEqual(filter(inventory,{...defaults(),transaction:'for-sale-or-lease'}).map(f=>f.id),[2]);assert.deepEqual(filter(inventory,{...defaults(),type:'land',transaction:'ground-lease'}).map(f=>f.id),[4]);});
test('SF boundaries, available-first fallback, and acreage never treated as SF',()=>{assert.deepEqual(filter(inventory,{...defaults(),size:'under-5000-sf'}).map(f=>f.id),[1]);assert.equal(filter(inventory,{...defaults(),size:'5000-10000-sf'}).length,0);assert.deepEqual(filter(inventory,{...defaults(),size:'50000-plus-sf'}).map(f=>f.id),[3]);assert.deepEqual(filter(inventory,{...defaults(),type:'land',size:'2-5-acres'}).map(f=>f.id),[4]);assert.equal(filter(inventory,{...defaults(),type:'land',size:'under-2-acres'}).length,0);});
test('areas use the same overlapping Atlas bounds and combine with filters',()=>{const west=areas.find(a=>a.value==='west-houston');assert.ok(west.bounds);const outside={...inventory[0],geometry:{type:'Point',coordinates:[0,0]}};assert.equal(filter([outside],{...defaults(),area:'west-houston'}).length,0);assert.equal(filter(inventory,{...defaults(),type:'retail',area:'west-houston'}).length,1);});
test('URL round-trip, unknown parameter rejection and reset to base',()=>{const types=['retail','industrial-flex','land'],tx=['for-lease','for-sale'];const filters=fromURL('?type=industrial-flex&transaction=for-lease&size=10000-25000-sf&area=west-houston',types,tx);assert.equal(toURL('https://example.com/properties/',filters),'/properties/?type=industrial-flex&transaction=for-lease&size=10000-25000-sf&area=west-houston');assert.deepEqual(fromURL('?type=bad&transaction=bad&size=bad&area=bad',types,tx),defaults());assert.equal(fromURL('?type=land&size=10000-25000-sf',types,tx).size,'');assert.equal(toURL('https://example.com/properties/?type=retail',defaults()),'/properties/');});
test('Featured respects metadata, Newest dates, Largest keeps unit groups separate',()=>{const featured={...inventory[0],properties:{...inventory[0].properties,directory:{featured:true,publishedAt:'2025-01-01'}}};assert.equal(sort([featured,...inventory.slice(1)],'featured')[0].id,1);assert.deepEqual(sort(inventory,'newest').map(f=>f.id),[4,3,2,1]);assert.deepEqual(sort(inventory,'largest').map(f=>f.id),[3,2,1,4]);assert.deepEqual(inventory.map(f=>f.id),[1,2,3,4]);});
test('safe card formatting preserves null/suppressed price and local URL policy',()=>{const p=f(5,'land','for-sale',null,null,2.21,{permalink:'https://example.com/properties/land/',image:{url:'https://elsewhere.test/image.jpg'},pricing:{salePrice:null,priceDisplay:null,leaseRateDisplay:null},propertyHighlights:['Real highlight']});const card=cardData(p,'https://example.com');assert.equal(card.image,null);assert.equal(card.permalink,'https://example.com/properties/land/');assert.ok(!card.metrics.some(m=>m.label==='PRICE'));assert.ok(!/NaN|undefined|null/.test(JSON.stringify(card.metrics)));assert.equal(card.metrics[0].value,'2.21 AC');});
test('mobile scanning metrics use available SF and rate, or land acreage without suppressed pricing',()=>{
 const industrial=cardData(f(6,'industrial-flex','for-lease',11273,37309,1.82,{pricing:{leaseRateDisplay:'$9.75–$11.50/SF/YR'}}),'https://example.com');
 assert.deepEqual(industrial.mobileMetrics.map(i=>industrial.metrics[i].label),['AVAILABLE','LEASE RATE']);
 const land=cardData(f(7,'land','for-sale',null,90000,2.21,{pricing:{salePrice:null,priceDisplay:null}}),'https://example.com');
 assert.deepEqual(land.mobileMetrics.map(i=>land.metrics[i]),[{label:'SITE',value:'2.21 AC'}]);
});
