import {AREAS,usableSf,propertyMetric} from '../../atlas/src/filters.js';
import {focusData} from '../../atlas/src/focus-data.js';
export const AREA_KEYS={'west-houston':'west','north-houston':'north','southwest-houston':'southwest','katy-richmond':'katy','humble-atascocita':'humble'};
export const areas=Object.entries(AREA_KEYS).map(([value,key])=>({value,...AREAS[key]}));
export const SF=[['','Any Size'],['under-5000-sf','Under 5,000 SF',0,5000],['5000-10000-sf','5,000–10,000 SF',5000,10000],['10000-25000-sf','10,000–25,000 SF',10000,25000],['25000-50000-sf','25,000–50,000 SF',25000,50000],['50000-plus-sf','50,000+ SF',50000,Infinity]];
export const ACRES=[['','Any Size'],['under-2-acres','Under 2 Acres',0,2],['2-5-acres','2–5 Acres',2,5],['5-20-acres','5–20 Acres',5,20],['20-plus-acres','20+ Acres',20,Infinity]];
export const defaults=()=>({type:'',transaction:'',size:'',area:''});
export function fromURL(search,types,transactions){const params=new URLSearchParams(search),value=defaults(),aliases={type:'property_type',transaction:'transaction_type'};for(const key of Object.keys(value))value[key]=params.get(key)||(aliases[key]?params.get(aliases[key]):'')||'';if(!types.includes(value.type))value.type='';if(!transactions.includes(value.transaction))value.transaction='';if(!Object.hasOwn(AREA_KEYS,value.area))value.area='';if(!(value.type==='land'?ACRES:SF).some(o=>o[0]===value.size))value.size='';return value;}
export function toURL(base,filters){const url=new URL(base);url.search='';url.hash='';for(const [key,value] of Object.entries(filters))if(value)url.searchParams.set(key,value);return url.pathname+url.search;}
export function filter(features,filters){return features.filter(f=>{const p=f.properties,land=p.propertyType?.slug==='land';if(filters.type&&p.propertyType?.slug!==filters.type)return false;if(filters.transaction&&p.transactionType?.slug!==filters.transaction&&!(p.transactionType?.slug==='for-sale-or-lease'&&['for-sale','for-lease'].includes(filters.transaction)))return false;const range=(filters.type==='land'?ACRES:SF).find(o=>o[0]===filters.size),size=land?p.metrics?.lotAcres:usableSf(p);if(range?.length===4&&(land!==(filters.type==='land')||!Number.isFinite(size)||size<=0||size<range[2]||size>=range[3]))return false;const bounds=areas.find(a=>a.value===filters.area)?.bounds,[x,y]=f.geometry.coordinates;return !bounds||(x>=bounds[0][0]&&x<=bounds[1][0]&&y>=bounds[0][1]&&y<=bounds[1][1]);});}
export function sort(features,order){return [...features].sort((a,b)=>{const x=a.properties,y=b.properties,newest=()=>((Date.parse(y.directory?.publishedAt)||0)-(Date.parse(x.directory?.publishedAt)||0))||b.id-a.id;if(order==='featured'){const featured=Number(!!y.directory?.featured)-Number(!!x.directory?.featured);return featured||newest();}if(order==='largest'){const landX=x.propertyType?.slug==='land',landY=y.propertyType?.slug==='land';if(landX!==landY)return landX?1:-1;const sizeX=landX?x.metrics?.lotAcres:usableSf(x),sizeY=landY?y.metrics?.lotAcres:usableSf(y);return (Number.isFinite(sizeY)?sizeY:-1)-(Number.isFinite(sizeX)?sizeX:-1)||newest();}return newest();});}
export function cardData(feature,origin){const data=focusData(feature,origin);if(!data)return null;const p=feature.properties,d=p.directory?.details??{},land=p.propertyType?.slug==='land',format=n=>n.toLocaleString('en-US',{maximumFractionDigits:2});
 const useful=[];const push=(label,n,suffix='')=>{if(Number.isFinite(n)&&n>0)useful.push({label,value:format(n)+suffix});};
 if(!land){if(['office','office-condo'].includes(p.propertyType?.slug)){if(d.buildingClass)useful.push({label:'Building class',value:d.buildingClass});if(d.parkingRatio)useful.push({label:'Parking',value:d.parkingRatio});else push('Parking',d.parkingSpaces,' spaces');}else if(p.propertyType?.slug==='industrial-flex')push('Clear height',d.clearHeightFt,' FT');else if(p.propertyType?.slug==='retail')push('Traffic',d.trafficCount,' VPD');}
 const result={...data,primary:land?(Number.isFinite(p.metrics?.lotAcres)&&p.metrics.lotAcres>0?format(p.metrics.lotAcres)+' AC':'Contact for availability'):propertyMetric(p),metrics:[...data.metrics.filter(m=>!land||!['AVAILABLE','BUILDING'].includes(m.label)),...useful].filter((v,i,all)=>all.findIndex(x=>x.label===v.label)===i).slice(0,5),highlights:data.highlights.slice(0,3),featured:!!p.directory?.featured};
 const first=result.metrics.findIndex(m=>land?m.label==='SITE':['AVAILABLE','BUILDING'].includes(m.label));const rate=result.metrics.findIndex(m=>/rate|price/i.test(m.label));result.mobileMetrics=[first<0?0:first,rate>=0?rate:(first<0?1:first+1)].filter((i,n,a)=>i<result.metrics.length&&a.indexOf(i)===n);return result;
}
